# Generated by Django 5.0.6 on 2024-06-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anemometru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoarea_medie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ceata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceata', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lumina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoarea_medie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Masuratoare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataMasuratoare', models.CharField(max_length=100)),
                ('timpMasuratoare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoarea_medie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Umiditate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoarea_medie', models.IntegerField()),
            ],
        ),
    ]
